#cloud-config

hostname: code-server

package_upgrade: true

timezone: Asia/Shanghai

users:
  - name: %%user%%
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: ubuntu-code-server

runcmd:
  - [sudo, -u, %%user%%, sh, -c, "curl -fsSL https://code-server.dev/install.sh | sh"]
  - [sudo, -u, %%user%%, sh, -c, "systemctl enable --now code-server@%%user%%"]
  - [sudo, -u, %%user%%, sh, -c, "systemctl restart code-server@%%user%%"]
  - [loginctl, enable-linger, %%user%%]
  - [echo, runcmd initialization finished]
